spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    platform: postgres
    url: jdbc:postgresql://192.168.160.116:5432/mes
    username: postgres
    password: abc@123
    driverClassName: org.postgresql.Driver
server:
  port: 8082
  error.include-message: always